/* Exploratory Data Analysis: Database Exploration: 

1. Explore ALL objects in the Database.*/
select
*
from INFORMATION_SCHEMA.TABLES;

-- 2. Explore all columns in the database.
select
*
from information_schema.columns;

/* Exploratory Data Analysis: Dimensions Exploration:

1. Explore ALL countries the customers come from */
select 
distinct
Country
from [dbo].[gold.dim_customers];
/* Explore All categories "The Major Divisions" */
select
distinct 
category,subcategory,product_name
from [dbo].[gold.dim_products];
/* Exploratory Data Analysis: Date Exploration: 

1. Find the date of the first and last order.
2. Find the timespan of sales*/
select
min(order_date) AS [First Order Date],
max(order_date) AS [Last Order Date],
datediff(year,min(order_date),max(order_date)) [Timespan of Orders]
from [dbo].[gold.fact_sales];

/* Find the youngest and oldest customer */
select
min(birthdate) AS [Oldest Customer Birthdate],
datediff(year, min(birthdate), getdate()) AS [Oldest Customer Age],
max(birthdate) AS [Youngest Customer Birthdate],
datediff(year,max(birthdate), getdate()) AS [Youngest Customer Age]
from [dbo].[gold.dim_customers];
/* Exploratory Data Analysis: Measures Exploration 

-- 1. Find the total Sales */
select
sum(sales_amount) [Total Sales] 
from [dbo].[gold.fact_sales];
-- 2. Find how many items are sold. 
select
sum(quantity) [Total Quantity]
from [dbo].[gold.fact_sales];
-- 3. Find the average selling price. 
select
avg(price) [Average Price]
from [dbo].[gold.fact_sales];
-- 4. Find the total number of orders.
select
count(distinct(order_number)) [Total Number of Orders]
from [dbo].[gold.fact_sales];
-- 5. Find the total number of products.
select
count(distinct(product_name)) [Total Number of Products]
from [dbo].[gold.dim_products];
-- 6. Find the total number of customers. 
select
count(distinct(customer_key)) [Total Number of Customers]
from [dbo].[gold.dim_customers];
-- 7. Find the total number of customers that has placed an order. 
select
count(distinct(customer_key)) [Number of Customers that Has Placed An Order]
from [dbo].[gold.fact_sales];
-- 8. Generate report that shows all key metrics of the business. 
select 
'Total Sales' AS [Measure Name],
sum(sales_amount) AS [Measure Value]
from [dbo].[gold.fact_sales]
union all 
select 
'Total Quantity' AS [Measure Name],
sum(quantity) AS [Measure Value]
from [dbo].[gold.fact_sales]
union all 
select
'Average Price' AS [Measure Name],
avg(price) [Measure Value]
from [dbo].[gold.fact_sales]
union all
select
'Total Number of Orders' AS [Measure Name],
count(distinct(order_number)) [Measure Value]
from [dbo].[gold.fact_sales]
union all 
select
'Total Number of Products' AS [Measure Name],
count(distinct(product_name)) AS [Measure Value]
from [dbo].[gold.dim_products]
union all 
select
'Total Number of Customers' AS [Measure Name],
count(distinct(customer_key)) [Total Number of Customers]
from [dbo].[gold.dim_customers]
union all
select
'Total Number of Customers That Has Placed An Order' AS [Measure Name],
count(distinct(customer_key)) [Number of Customers that Has Placed An Order]
from [dbo].[gold.fact_sales];
/* Exploratory Data Analysis: Magnitude Analysis:

1. Find total customers by countries. */
select
country,
sum(customer_key)[Number of Customers]
from [dbo].[gold.dim_customers] 
group by country;
-- 2. Find total customers by gender */ 
select
gender,
count(customer_key) [Total Customers by Gender]
from [dbo].[gold.dim_customers] 
group by gender;
-- 3. Find total products by category.
select
category,
count(distinct(product_key)) [Total Products by Category]
from [dbo].[gold.dim_products]
group by category
order by [Total Products by Category] desc;
-- 4. Find the average costs in each category. 
select
category,
avg(cost) [Average Products by Category]
from [dbo].[gold.dim_products]
group by category
order by [Average Products by Category] desc;
-- 5. Find the total revenue generated by each category. 
select
p.category,
sum(sales_amount) [Total Revenue Generated By Each Category]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_products] as p
on p.product_key = f.product_key
group by 
	p.category
order by [Total Revenue Generated By Each Category] desc;
-- 6. Find the total revenue generated by each customer. 
select
	c.customer_key,
	c.first_name, 
	c.last_name,
sum(f.sales_amount) [Total Revenue Generated By Each Customer]
from [dbo].[gold.fact_sales] AS f
left join [dbo].[gold.dim_customers] AS c
on c.customer_key = f.customer_key
group by
	c.customer_key,
	c.first_name, 
	c.last_name
order by [Total Revenue Generated By Each Customer] DESC;
-- 7. What is the distribution of sold items across countries. 
select
	c.country,
	sum(f.quantity) AS [Distribution By Each Countries]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_customers] as c
on c.customer_key = f.customer_key
group by c.country
order by [Distribution By Each Countries] desc;
/* Exploratory Data Analysis: Ranking Analysis 

1. Which 5 products generate the highest revenue.
* Use the Group By Method
* Use the Rank Method */
-- Group By Method: 
select top 5
	p.product_name,
	sum(f.sales_amount) AS [Top 5 products]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_products] as p
on p.product_key = f.product_key
group by p.product_name
order by [Top 5 products] desc;
-- Rank Method:
select
*
from 
(
select
	p.product_name,
	sum(f.sales_amount) AS [Total Revenue],
	rank() over(order by sum(f.sales_amount) desc) AS [Top Ranking]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_products] as p
on p.product_key = f.product_key
group by p.product_name
)t
where [Top Ranking] <= 5;
/* 2. What are the top 5 worst-performing products in terms of sales. 
* Use the Group By Method
* Use the Rank Method */
-- * Group By Method: 
select top 5
	p.product_name,
	sum(f.sales_amount) AS [Bottom 5 products]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_products] as p
on p.product_key = f.product_key
group by p.product_name
order by [Bottom 5 products] asc;
-- * Rank Method:
select 
*
from
(
select 
	p.product_name,
	sum(f.sales_amount) AS [Total Revenue],
	rank() over(order by sum(f.sales_amount) asc)  AS [Bottom Ranking]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_products] as p
on p.product_key = f.product_key
group by p.product_name
)t 
where [Bottom Ranking] <= 5;
-- 3. Find the top 10 customers who have generated the highest revenue. 
-- * Group By Method:
select top 10
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) AS [Top 10 Customers]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_customers] as c
on c.customer_key = f.customer_key
group by
	c.customer_key,
	c.first_name,
	c.last_name
order by [Top 10 Customers] desc;
-- * Rank Method:
select
*
from
(
select 
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) AS [Total Revenue],
	rank() over(order by sum(f.sales_amount) desc) AS [Top 10 Customers]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_customers] as c
on c.customer_key = f.customer_key
group by
	c.customer_key,
	c.first_name,
	c.last_name
)t 
where [Top 10 Customers] <= 11;
-- 4. Find the three customers with the fewest orders placed. 
-- * Group BY Method
select Top 3
	c.customer_key,
	c.first_name,
	c.last_name,
	count(f.order_number) AS [Fewest Number of Orders]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_customers] as c
on c.customer_key = f.customer_key
group by 
	c.customer_key,
	c.first_name,
	c.last_name
order by [Fewest Number of Orders] ASC;
-- * Rank Method 
select
*
from
(
select 
	c.customer_key,
	c.first_name,
	c.last_name,
	count(f.order_number) AS [Fewest Number of Orders],
	row_number() over(order by count(f.order_number)) AS [Ranking]
from [dbo].[gold.fact_sales] as f
left join [dbo].[gold.dim_customers] as c
on c.customer_key = f.customer_key
group by 
	c.customer_key,
	c.first_name,
	c.last_name
)t 
where [Ranking] <=  3;